runtime: nodejs18

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(js|css|png|jpg|svg|json|html))
    static_files: build/\1
    upload: build/.*\.(js|css|png|jpg|svg|json|html)

  - url: /upload
    script: auto

  - url: /test
    script: auto

  - url: /.*
    static_files: build/index.html
    upload: build/index.html